### ISSUE TITLE
Unable to login with correct credentials

### ISSUE THREAD

**Issue by Jatin-73** [suresh-ramani/larasanctum-authvue#1]
I have setup project as given instructions. but when i try to login with correct credentials. Then,  '{"message":"Unauthenticated."}' message coming in user API. I'm Unable to login.

![Screenshot from 2021-10-27 09-10-30](https://user-images.githubusercontent.com/65058938/138996102-e306e12b-edf5-40e5-a372-72066307c5e4.png).

**Comment by suresh-ramani** [comment]
Hello

Can you share the database record for this user?

Thank You.

**Comment by Jatin-73** [comment]
https://prnt.sc/1xqm95h
Username: jatin@gmail.com
Password: admin@123

Sql query for this user
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Jack', 'jatin@gmail.com', NULL, '$2y$10$DHzN.ZOZq96bINWR3/6P3OIkOh6xej1ROgHZhe2N4OZDNCsx65CXi', NULL, '2021-10-29 10:48:15', '2021-10-29 10:48:15');

Same error happened when i try register as a new user.
![Screenshot from 2021-10-29 22-00-17](https://user-images.githubusercontent.com/65058938/139470704-dbafc906-14a5-44fb-aeec-3f94818ae335.png)

**Comment by suresh-ramani** [comment]
Hello,

I need to check your code.

Can you share your code with me on github?

Thank You.

**Comment by Jatin-73** [comment]
I have uploaded my project code on public repository. Also i have uploaded SQL file in database folder. 
and i have modified my .env.example file same as .env for reference. Please check that.

https://github.com/Jatin-73/laravel-vue-sanctum/

**Comment by mdasiff** [comment]
Same error i'm getting 
![image](https://user-images.githubusercontent.com/35130721/139623349-c3c9c143-8702-4273-a3b1-1fbe9894c797.png)

**Comment by mdasiff** [comment]
Might be user route are missing.

**Comment by suresh-ramani** [comment]
Hello

SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1

Update this variable in your .env file and check again.

**Comment by mdasiff** [comment]
Thanx Suresh, I have uncommented below line, and now its working fine
app\Http\Kernel.php
```
'api' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

**Comment by Jatin-73** [comment]
> Hello
> 
> SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1
> 
> Update this variable in your .env file and check again.

Thanks Suresh, For your effective solution. it's working now.
